<style>
   .rowstyle0 {background: #F9F9F9; padding: 5px; font-size: 15px; margin-right:15px;}
   .rowstyle1 {background: #F0F0F0; padding: 5px; font-size: 15px; margin-right:15px;}
</style>
   <h2 align="center">Spam</h2>
<?php

require_once('plugins/webtools/webtools/functions.php');
require_once('functions.inc');

$rcmail = rcmail::get_instance();
$subhead = $rcmail->config->get('spam_subhead');
?>

<div id="webtools-subhead">
	<?=$subhead?>
</div>

<div id="webtools-innerbox" style="padding:25px" class="ui-widget ui-widget-content ui-corner-all">

<?php
/* This code handles the spam ajax requests that come in. */
if ($_POST['page'] == "Submit")
{
	console($_POST);
	$rcmail = rcmail::get_instance();
	$header = $rcmail->config->get('warning_comment');
	//$header  = "################################################\n";
	//$header .= "# THIS FILE WAS CREATED BY A WEBTOOL.          #\n";
	//$header .= "# DO NOT EDIT THIS FILE BY HAND.               #\n";
	//$header .= "################################################\n\n";
	$files['mailfilter-spam'] = $header;
	$files['mailfilter-spam-blacklist'] = "";
	$files['mailfilter-spam-whitelist'] = "";
	$files['mailfilter-spam'] .= "#spamlevel: " . $_POST['spamlevel'] . "\nSPAMLEVEL='";
	for ($i=0; $i<intval($_POST['spamlevel']); $i++) $files['mailfilter-spam'] .= "*";
	$files['mailfilter-spam'] .= "'\n";
	$files['mailfilter-spam'] .= "#spamfolder: ";
	$errors = array();
	if ($_POST['tagged-spam'] == "folder") $files['mailfilter-spam'] .= $_POST['spam-folder'] . "\n" . "SPAMFOLDER='" . $_POST['spam-folder'] . "'\n";
	else if ($_POST['tagged-spam'] == "delete") $files['mailfilter-spam'] .= "\nSPAMFOLDER=''\n";
	else if ($_POST['tagged-spam'] == "ourfolder") 
	{
		if (is_numeric($_POST['ourfolder-dayskeep'])) {
			$files['mailfilter-spam'] .= "AUTO-DELETED-SPAM" . "\n" . "SPAMFOLDER='AUTO-DELETED-SPAM'\n";
			$files['mailfilter-autodeletedspam'] = $header . "#cleanupdays: " . $_POST['ourfolder-dayskeep'] . "\n" . $_POST['ourfolder-dayskeep'];
		} else {
			$errors['ourfolder-dayskeep'] = 'The number of days must be an integer.';
		}

	}
   foreach ($_POST['blacklist-address'] as $address)
   {
      if (empty($address)) continue;
	  if (email_valid($address)){ //allow invalid DNS
         $files['mailfilter-spam-blacklist'] .= "#blacklist-user: " . $address . "\n";
         $address = str_replace (".", "\.", $address);
         $files['mailfilter-spam-blacklist'] .= "^" . $address . "\n";
	  }
   }
   foreach ($_POST['blacklist-domain'] as $domain)
   {
      if (empty($domain)) continue;
	  if (validate_spam_domain($domain)) {
         $files['mailfilter-spam-blacklist'] .= "#blacklist-domain: " . $domain . "\n";
         $domain = str_replace (".", "\.", $domain);
         $domain .= "\n";
         $subdomain = "@.*\." . $domain;
         $domain = "@" . $domain;
         $files['mailfilter-spam-blacklist'] .= $domain . $subdomain;
	  }
   }
   if (!empty($files['mailfilter-spam-blacklist'])) $files['mailfilter-spam-blacklist'] = $header . $files['mailfilter-spam-blacklist'];
   foreach ($_POST['whitelist-address'] as $address)
   {
      if (empty($address)) continue;
	  if(email_valid($address)) {
         $files['mailfilter-spam-whitelist'] .= "#whitelist-user: " . $address . "\n";
         $address = str_replace (".", "\.", $address);
         $files['mailfilter-spam-whitelist'] .= "^" . $address . "\n";
	  }
   }
   foreach ($_POST['whitelist-domain'] as $domain)
   {
      if (empty($domain)) continue;
	  if (validate_spam_domain($domain)) {
         $files['mailfilter-spam-whitelist'] .= "#whitelist-domain: " . $domain . "\n";
         $domain = str_replace (".", "\.", $domain);
         $domain .= "\n";
         $subdomain = "@.*\." . $domain;
         $domain = "@" . $domain;
         $files['mailfilter-spam-whitelist'] .= $domain . $subdomain;
	  }
   }
   if (!empty($files['mailfilter-spam-whitelist'])) $files['mailfilter-spam-whitelist'] = $header . $files['mailfilter-spam-whitelist'];
   foreach ($files as $filename => $contents)
   {
      write_file ("Maildir/" . $filename, $contents);
      if (empty($contents))
         remove_file("Maildir/$filename");
   }
    echo ("<div id='successdiv' style='border:1px solid #11aa00;margin:15px;padding:10px;background:#aaff99;font-size:15px;text-align:center;'>Settings successfully updated!</div>" .
    "<script type=\"text/javascript\">setTimeout(\"$('#successdiv').hide('slow')\",5000);</script>"); // pretty little div

}
{
	$config['spamlevel'] = 4;
	if (have_file ("Maildir/mailfilter-spam", $result))
	{
		for ($i = 4; $i < count($result); $i++)
		{
			$line = $result[$i];
			if (strchr($line, '#') != false)
			{
				$line = str_replace (array("#", " "), "", $line);
				$vals = explode (':', $line);
				$config[$vals[0]] = $vals[1];
			}
		}
	}
	$config['cleanupdays'] = 14;
	if (have_file ("Maildir/mailfilter-autodeletedspam", $result))
	{
		if (strchr($result[5], '#') != false)
		{
			$result[5] = str_replace (array("#", " "), "", $result[5]);
			$vals = explode (':', $result[5]);
			$config[$vals[0]] = $vals[1];
		}
	}
	if (have_file ("Maildir/mailfilter-spam-blacklist", $result))
	{
		foreach ($result as $line)
		{
			if (strchr($line, '#'))
			{
				$line = str_replace (array("#", " "), "", $line);
				if (strstr($line, "blacklist-user"))
					$config['blacklist-address'][] = end(explode(':', $line));
				else if (strstr($line, "blacklist-domain"))
					$config['blacklist-domains'][] = end(explode(':', $line));
			}
		}
	}
	if (have_file ("Maildir/mailfilter-spam-whitelist", $result))
	{
		foreach ($result as $line)
		{
			if (strchr($line, '#'))
			{
				$line = str_replace (array("#", " "), "", $line);
				if (strstr($line, "whitelist-user"))
					$config['whitelist-address'][] = end(explode(':', $line));
				else if (strstr($line, "whitelist-domain"))
					$config['whitelist-domains'][] = end(explode(':', $line));
			}
		}
	}
	if ($config['spamfolder'] == "AUTO-DELETED-SPAM")
	{
		$config['ourfolder'] = true;
		$config['spamfolder'] = "";
	}
	else if ($config['spamfolder'] != "") $config['folder'] = true;
	else if ($config['spamfolder'] == "") $config['delete'] = true;
?>
	<script type="text/javascript">
	$(function(){
		$('#slider').slider({
			slide: function(event, ui) { document.getElementById('level').value = ui.value; document.getElementById('slider-value').innerHTML=ui.value; },
				min: 1, max: 30, value: <?=$config['spamlevel']?>
		});
	});
	</script>
	   <style> #slider .ui-slider-handle { border-color: #CCCCCC; background: #FEFEFE; } 
   .webtools-select { width: 25em; }</style>
   <form method="POST" action="?_task=dummy&_action=plugin.webtoolsspam" id="spam-form" onsubmit="return validate_edit()">
	  <div style="padding-left:10px; padding-right:10px; margin-bottom:25px;" class="ui-widget ui-widget-content ui-corner-all">
		 <h4>Required Spam Settings</h4>
		 <p>
			A spam filter level of 5 is recommended unless you are choosing to delete mail tagged as spam; in this case the recommended
			level is 10.  The lower this number is, the stricter the spam filter will be.
		 </p>
		 <p>
			<input type='hidden' name='spamlevel' value='<?=$config['spamlevel']?>' id='level'>
			<div id="slider"style="width:90%;float:left"></div>
			<div style="text-align:center;" id="slider-value"><?=$config['spamlevel']?></div>
			<div style="width:90%">
			   <div style="font-size:11px;float:left;"><i>Strict</i></div>
			   <div style="font-size:11px;float:right;"><i>Lenient</i></div>
			</div>
		 </p><br>
		 What would you like the filter to do with mail marked as spam?
<?php
	$cleanup_days = $config['cleanupdays'];
	//if we're returning from the form.
	if(!empty($_POST['ourfolder-dayskeep'])) {
		$cleanup_days = $_POST['ourfolder-dayskeep'];
	}
?>

	 <table><tr><td>
			<input type='radio' name='tagged-spam' value='ourfolder' <?=($config['ourfolder']?"checked":"")?>>
			Store the spam in a folder called 'AUTO-DELETED-SPAM'. 
			Keep it for <input type='text'  class="ui-button ui-widget ui-corner-all" name='ourfolder-dayskeep' size=3 maxlength=3 value='<?=$cleanup_days; ?>'> days.
		 </td></tr></table>
		 <table><tr><td>
			<input id="radio-spam-folder" type='radio' name='tagged-spam' value='folder' <?=($config['folder']?"checked":"")?>>
		Store the spam in this folder:&nbsp;</td><td>
			<?=make_folder_select_spam ($config['spamfolder'])?></td>
		 </tr></table>
		 <table><tr><td>
			<input type='radio' name='tagged-spam' value='delete' <?=($config['delete']?"checked":"")?>>
			Delete the spam.
		 </td></tr></table>
	  </div>
	  <div style="padding-left: 10px; padding-right:10px margin-bottom:15px;" class="ui-widget ui-widget-content ui-corner-all">
		 <h4>Optional Spam Filters</h4>
		 <div id="blacklist-address">
			<p>
			   Always treat mail from these addresses as spam:
			</p>
<?php
	foreach ($config['blacklist-address'] as $address)
		//echo ('<p><input type="text" name="blacklist-address[]" size=40 maxlength=129 value="'.$address.'"></p>');
		echo make_box ("blacklist-address", $address, 'validate_email_dumb');
?>
			<!-- end of saved fields -->
			<div id='blacklist-address-button' style="margin:10px 10px 10px 18px; width:32px"
				 class="ui-button ui-widget ui-state-default ui-corner-all">
			   <a href="#" onclick="add_input('blacklist-address', 'validate_email_dumb')"><img src="plugins/webtools/webtools/spam/img/list-add.png"></a>
			</div>
		 </div>
		 <div id="blacklist-domain">
			<p>
			  Always treat mail from these domains as spam:</p>
<?php
	foreach ($config['blacklist-domains'] as $address)
		//  echo ('<p><input type="text" name="blacklist-domain[]" size=40 maxlength=129 value="'.$address.'"></p>');
		echo make_box ("blacklist-domain", $address, 'validate_domain_dumb');
?>
			<!-- end of saved fields -->
			<div id='blacklist-domain-button' style="margin:10px 10px 10px 18px; width:32px"
				 class="ui-button ui-widget ui-state-default ui-corner-all">
			   <a href="#" onclick="add_input('blacklist-domain', 'validate_domain_dumb')"><img src="plugins/webtools/webtools/spam/img/list-add.png"></a>
			</div>
		 </div>
		 <div id="whitelist-address">
			<p>Never treat mail from these addresses as spam:</p>
<?php
	foreach ($config['whitelist-address'] as $address)
		// echo ('<p><input type="text" name="whitelist-address[]" size=40 maxlength=129 value="'.$address.'"></p>');
		echo make_box ("whitelist-address", $address, 'validate_email_dumb');
?>
			<!-- end of saved fields -->
			<div id='whitelist-address-button' style="margin:10px 10px 10px 18px; width:32px"
				 class="ui-button ui-widget ui-state-default ui-corner-all">
			   <a href="#" onclick="add_input('whitelist-address', 'validate_email_dumb')"><img src="plugins/webtools/webtools/spam/img/list-add.png"></a>
			</div>
		 </div>
		 <div id="whitelist-domain">
			<p>Never treat mail from these domains as spam:</p>
<?php
	foreach ($config['whitelist-domains'] as $address)
		//echo ('<p><input type="text" name="whitelist-domain[]" size=40 maxlength=129 value="'.$address.'"></p>');
		echo make_box ("whitelist-domain", $address, 'validate_domain_dumb');
?>
			<!-- end of saved fields -->
			<div id='whitelist-domain-button' style="margin:10px 10px 10px 18px; width:32px"
				 class="ui-button ui-widget ui-state-default ui-corner-all">
			   <a href="#" onclick="add_input('whitelist-domain', 'validate_domain_dumb')"><img src="plugins/webtools/webtools/spam/img/list-add.png"></a>
			</div>
		 </div>
		 <div style="height:15px"></div>
	  </div>
	  <input type="hidden" name='page' value='Submit'>
	  <button class="ui-button ui-widget ui-state-default ui-corner-all" style="margin:10px;">Submit</button>
   </form>
</div>
<?php
}
?>
<div id="webtools-instructions" class="webtools-accordion">
   <div>
	  <h3><a id="instr-header" href="#">Help</a></h3>
	  <div id="instr-content">
		 <?=$rcmail->config->get('spam_help')?>
	  </div>
   </div>
</div>

